#!/usr/bin/env bash
node samsa-cli.js GFV/Changa/Changa-VariableFont_wght.ttf -i named -o Changa-VariableFont_wght
node samsa-cli.js GFV/Comfortaa/Comfortaa-VariableFont_wght.ttf -i named -o Comfortaa-VariableFont_wght
node samsa-cli.js GFV/Crimson_Pro/CrimsonPro-Italic-VariableFont_wght.ttf -i named -o CrimsonPro-Italic
node samsa-cli.js GFV/Crimson_Pro/CrimsonPro-VariableFont_wght.ttf -i named -o CrimsonPro-VariableFont_wght
node samsa-cli.js GFV/Dancing_Script/DancingScript-VariableFont_wght.ttf -i named -o DancingScript-VariableFont_wght
node samsa-cli.js GFV/Dosis/Dosis-VariableFont_wght.ttf -i named -o Dosis-VariableFont_wght
node samsa-cli.js GFV/EB_Garamond/EBGaramond-Italic-VariableFont_wght.ttf -i named -o EBGaramond-Italic
node samsa-cli.js GFV/EB_Garamond/EBGaramond-VariableFont_wght.ttf -i named -o EBGaramond-VariableFont_wght
node samsa-cli.js GFV/Exo_2/Exo2-Italic-VariableFont_wght.ttf -i named -o Exo2-Italic
node samsa-cli.js GFV/Exo_2/Exo2-VariableFont_wght.ttf -i named -o Exo2-VariableFont_wght
node samsa-cli.js GFV/Faustina/Faustina-Italic-VariableFont_wght.ttf -i named -o Faustina-Italic
node samsa-cli.js GFV/Faustina/Faustina-VariableFont_wght.ttf -i named -o Faustina-VariableFont_wght
node samsa-cli.js GFV/Fira_Code/FiraCode-VariableFont_wght.ttf -i named -o FiraCode-VariableFont_wght
node samsa-cli.js GFV/Fira_Code 2/FiraCode-VariableFont_wght.ttf -i named -o FiraCode2-VariableFont_wght
node samsa-cli.js GFV/Hepta_Slab/HeptaSlab-VariableFont_wght.ttf -i named -o HeptaSlab-VariableFont_wght
node samsa-cli.js GFV/Inter/Inter-VariableFont_slnt,wght.ttf -i named -o Inter-VariableFont_slnt
node samsa-cli.js GFV/Josefin_Sans/JosefinSans-Italic-VariableFont_wght.ttf -i named -o JosefinSans-Italic
node samsa-cli.js GFV/Josefin_Sans/JosefinSans-VariableFont_wght.ttf -i named -o JosefinSans-VariableFont_wght
node samsa-cli.js GFV/Jura/Jura-VariableFont_wght.ttf -i named -o Jura-VariableFont_wght
node samsa-cli.js GFV/Kreon/Kreon-VariableFont_wght.ttf -i named -o Kreon-VariableFont_wght
node samsa-cli.js GFV/Lemonada/Lemonada-VariableFont_wght.ttf -i named -o Lemonada-VariableFont_wght
node samsa-cli.js GFV/Literata-2/Literata-Italic-VariableFont_wght.ttf -i named -o Literata-Italic-VariableFont_wght
node samsa-cli.js GFV/Literata-2/Literata-VariableFont_wght.ttf -i named -o Literata-VariableFont_wght
node samsa-cli.js GFV/Lora/Lora-Italic-VariableFont_wght.ttf -i named -o Lora-Italic
node samsa-cli.js GFV/Lora/Lora-VariableFont_wght.ttf -i named -o Lora-VariableFont_wght
node samsa-cli.js GFV/Manuale/Manuale-Italic-VariableFont_wght.ttf -i named -o Manuale-Italic
node samsa-cli.js GFV/Manuale/Manuale-VariableFont_wght.ttf -i named -o Manuale-VariableFont_wght
node samsa-cli.js GFV/Markazi_Text/MarkaziText-VariableFont_wght.ttf -i named -o MarkaziText-VariableFont_wght
node samsa-cli.js GFV/Maven_Pro/MavenPro-VariableFont_wght.ttf -i named -o MavenPro-VariableFont_wght
node samsa-cli.js GFV/Muli/Muli-Italic-VariableFont_wght.ttf -i named -o Muli-Italic
node samsa-cli.js GFV/Muli/Muli-VariableFont_wght.ttf -i named -o Muli-VariableFont_wght
node samsa-cli.js GFV/Orbitron/Orbitron-VariableFont_wght.ttf -i named -o Orbitron-VariableFont_wght
node samsa-cli.js GFV/Oswald/Oswald-VariableFont_wght.ttf -i named -o Oswald-VariableFont_wght
node samsa-cli.js GFV/Playfair_Display/PlayfairDisplay-Italic-VariableFont_wght.ttf -i named -o PlayfairDisplay-Italic
node samsa-cli.js GFV/Playfair_Display/PlayfairDisplay-VariableFont_wght.ttf -i named -o PlayfairDisplay-VariableFont_wght
node samsa-cli.js GFV/Podkova/Podkova-VariableFont_wght.ttf -i named -o Podkova-VariableFont_wght
node samsa-cli.js GFV/Public_Sans/PublicSans-Italic-VariableFont_wght.ttf -i named -o PublicSans-Italic
node samsa-cli.js GFV/Public_Sans/PublicSans-VariableFont_wght.ttf -i named -o PublicSans-VariableFont_wght
node samsa-cli.js GFV/Quicksand/Quicksand-VariableFont_wght.ttf -i named -o Quicksand-VariableFont_wght
node samsa-cli.js GFV/Roboto_Slab/RobotoSlab-VariableFont_wght.ttf -i named -o RobotoSlab-VariableFont_wght
node samsa-cli.js GFV/Rokkitt/Rokkitt-VariableFont_wght.ttf -i named -o Rokkitt-VariableFont_wght
node samsa-cli.js GFV/Rosario-2/Rosario-Italic-VariableFont_wght.ttf -i named -o Rosario-Italic-VariableFont_wght
node samsa-cli.js GFV/Rosario-2/Rosario-VariableFont_wght.ttf -i named -o Rosario-VariableFont_wght
node samsa-cli.js GFV/Ruda/Ruda-VariableFont_wght.ttf -i named -o Ruda-VariableFont_wght
node samsa-cli.js GFV/Spartan/Spartan-VariableFont_wght.ttf -i named -o Spartan-VariableFont_wght
node samsa-cli.js GFV/Work_Sans-2/WorkSans-Italic-VariableFont_wght.ttf -i named -o WorkSans-Italic-VariableFont_wght
node samsa-cli.js GFV/Work_Sans-2/WorkSans-VariableFont_wght.ttf -i named -o WorkSans-VariableFont_wght
node samsa-cli.js GFV/Yanone_Kaffeesatz/YanoneKaffeesatz-VariableFont_wght.ttf -i named -o YanoneKaffeesatz-VariableFont_wght
